version: '3'

services:
  huddlenode0:
    container_name: huddlenode0
    image: "huddlelabs/huddle-env"
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
    environment:
      - ID=0
      - LOG=${LOG:-huddle.log}
    volumes:
      - ./build/node0:/root
      - ./build:/huddle:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  huddlenode1:
    container_name: huddlenode1
    image: "huddlelabs/huddle-env"
    ports:
      - "26666-26667:26656-26657"
      - "1318:1317"
      - "9091:9090"
    environment:
      - ID=1
      - LOG=${LOG:-huddle.log}
    volumes:
      - ./build/node1:/root
      - ./build:/huddle:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  huddlenode2:
    container_name: huddlenode2
    image: "huddlelabs/huddle-env"
    environment:
      - ID=2
      - LOG=${LOG:-huddle.log}
    ports:
      - "26676-26677:26656-26657"
      - "1319:1317"
      - "9092:9090"
    volumes:
      - ./build/node2:/root
      - ./build:/huddle:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  huddlenode3:
    container_name: huddlenode3
    image: "huddlelabs/huddle-env"
    environment:
      - ID=3
      - LOG=${LOG:-huddle.log}
    ports:
      - "26686-26687:26656-26657"
      - "1320:1317"
      - "9093:9090"
    volumes:
      - ./build/node3:/root
      - ./build:/huddle:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16
