FROM ubuntu:20.04

# Copy over binaries from the build-env
COPY --from=huddlelabs/builder:latest /code/build/huddle /usr/bin/huddle

EXPOSE 26656 26657 1317 9090

# Run huddle by default, omit entrypoint to ease using container with huddle
CMD ["huddle"]